name: "i have issues"

description: "consume the output of the previous action and create a new issue in the repository"

inputs:
    joke:
        description: "this will become the body of the created" 
    issue-title:
        description: "every issue needs a title, its nice to supply one"
        default: "a joke for you"
        required: true

runs:
    using: "node12"
    main: "index.js"